### ISSUE TITLE
Is proximity an attribute of conceptual model or can it be useful in some use cases?

### ISSUE THREAD

**Issue by JLK42** [opengeospatial/poi#95]
POIs may be used as an alert to tell a user about an attraction or issue along their trajectory.
Would there be any instances where a POI would have a property that indicates when a POI should be active in relation to something that is moving toward it?

**Comment by cperey** [comment]
The concept is fundamental. It is to alert users of a POI (or conditions of a POI).

The operation to determine how far away a POI is from another point is already implemented in every GIS platform. 
This is where we go from Static data to Dynamic data. Instead of searching for and pulling data, you're looking for an event-driven model (e.g., the information is pushed to a user only when certain conditions are met).

A query is not event-driven. You get the results when the request is placed and there is a response.

Our data model is not currently ready for pub-sub. Is there a way to do a general solution that will work for both (static/query as well as pub-sub event-driven model)?

The query or the event is a function of the individual user's position. The state of the POI is specific to a user. Is this criterion  met for me, now? 

Is there an instance in which there's something contained in the POI that acts as a "helper" for when the POI is useful?

In the future, we may enable relationships with Moving Features.

**Comment by cperey** [comment]
Is there a reason a POI may have more than one state? A property like status or state might be appropriate for some use cases. 

Open/closed status?
what events can trigger the state change? 

Chuck: a POI might be a much better mechanism about a state change than dumping an entire feature or data set. 
the question is: if I'm using a POI as an alert, what properties do I need and can we do this in a way that is more flexible (rather than less)?

To be explored further?! 

From routing perspective, what information is needed/what properties are needed? Please populate this issue with that information.

Code list?
Do you need a trigger date? 
Expiration date and time? 
what else that's not already in the model?

**Comment by cperey** [comment]
Action for @JLK42: develop requirements for these use cases!

**Comment by geofizzydrink** [comment]
@JLK42 This appears to be out of scope for the POI Spec (and data model) itself - but may be relevant to wider server/API infrastructures that may access POI resources.

Let's discuss further.

**Comment by cmheazel** [comment]
A software analytic has detected that a threshold has been crossed (ex. something has gotten too close). In an event-driven architecture, it would then publish an alert. The purpose of the alert is to inform interested parties that the threshold event has taken place and to provide minimal information about that event. If the data related to the event is large, the alert may also provide a link for accessing that data.
1. Is an alert a POI?
2. If so, what properties would it need?

**Comment by cmheazel** [comment]
On further thought, I think that while a POI can be an Alert, an Alert is not necessarily a POI.  Therefore we should not mandate Alert behavior and properties in the POI Standard.  If there is a need to standardize POIs as Alerts, then that would be the job of a profile of the POI Standard.

**Comment by cmheazel** [comment]
I think we can close this one.

**Comment by geofizzydrink** [comment]
Issue Closed
